### ISSUE TITLE
unhandled `Expr`s

### ISSUE THREAD

**Issue by aviatesk** [aviatesk/EscapeAnalysis.jl#23]
With the following diff and experiment, I found these `Expr`s are unhandled well right now:
```diff
diff --git a/src/EscapeAnalysis.jl b/src/EscapeAnalysis.jl
index bb3ca7b..ca4204a 100644
--- a/src/EscapeAnalysis.jl
+++ b/src/EscapeAnalysis.jl
@@ -195,6 +195,8 @@ __clear_escape_cache!() = empty!(GLOBAL_ESCAPE_CACHE)
 
 const Changes = Vector{Tuple{Any,EscapeInformation}}
 
+const UNANALYZED_EXPRS = Set{Symbol}()
+
 # TODO
 # - implement more builtin handling
 # - (related to above) do alias analysis to some extent
@@ -253,6 +255,7 @@ function find_escapes(ir::IRCode, nargs::Int)
                 elseif head === :enter || head === :leave || head === :pop_exception
                     continue
                 else # TODO: this is too conservative
+                    push!(UNANALYZED_EXPRS, head)
                     add_changes!(stmt.args[2:end], ir, Escape(), changes)
                 end
             elseif isa(stmt, PiNode)
```
```julia
julia> using EscapeAnalysis, Plots

julia> @analyze_escapes plot(rand(10,3));

julia> foreach(EscapeAnalysis.UNANALYZED_EXPRS) do x
           println("- [ ] `:$x`")
       end
```

So there are many TODOs:
- [x] `:gc_preserve_end`
- [x] `:throw_undef_if_not`
- [x] `:static_parameter`
- [x] `:the_exception`
- [x] `:splatnew`
- [x] `:copyast`
- [x] `:gc_preserve_begin`
- [x] `:undefcheck`
- [x] `:loopinfo`
- [x] `:foreigncall`
- [x] `:cfunction`
- [x] `:isdefined`
- [x] `:boundscheck` 

---

@TH3CHARLie do you want to tackle handling some of above ? Probably we can just ignore most of them if it's okay and then analysis may improve a bit.

**Comment by aviatesk** [comment]
Handled some of them in #25

**Comment by TH3CHARLie** [comment]
I want to tackle the `:foreigncall` case

**Comment by TH3CHARLie** [comment]
Updating status in this comment:

- [x] `foreigncall` #28 ready for review
- [x] `cfunctioncall` #29 failing test
- [x] `splatnew` #30 unable to produce test that not inline `splatnew`

**Comment by TH3CHARLie** [comment]
I plan to merge all three PRs even though some of them have no associated tests, the reason is to make the development of heap-to-stack optimization easier and more in sync with master. I plan to add a followup PR to fill the missing tests.

**Comment by aviatesk** [comment]
Thanks so much @TH3CHARLie , let me close this. We can keep iterating change these handling.
